import {Artikal} from "./models/artikal"

export const PRODUCTS: Artikal[] = [
    {"id": 1, "naziv": "Dell xps 13", "kratki_tekst": "10th Intel® Core™ i5-1035G1   Windows 10 Home \n Intel® UHD Graphics \n 8GB 3733MH \n 256GB M.2 PCIe ", "dugi_tekst": "10th Intel® Core™ i5-1035G1   Windows 10 Home \n Intel® UHD Graphics \n 8GB 3733MH \n 256GB M.2 PCIe ", "cijena": 2300, "popust": 30, "kolicina": 1, "img":"../../assets/images/download.jpg" , "tip": "laptop"},
    {"id": 2, "naziv": "Dell xps 15", "kratki_tekst": "10th Intel® Core™ i7-1035G1   Windows 10 Home \n Intel® UHD Graphics \n 8GB 3733MH \n 256GB M.2 PCIe ", "dugi_tekst": "10th Intel® Core™ i7-1035G1   Windows 10 Home \n Intel® UHD Graphics \n 8GB 3733MH \n 256GB M.2 PCIe ", "cijena": 2850, "popust": 30, "kolicina": 1,"img":"../../assets/images/download1.jpg", "tip": "laptop" },
    {"id": 3, "naziv": "Dell xps 13", "kratki_tekst": "10th Intel® Core™ i5-1035G1   Windows 10 Home \n Intel® UHD Graphics \n 8GB 3733MH \n 256GB M.2 PCIe ", "dugi_tekst": "10th Intel® Core™ i5-1035G1   Windows 10 Home \n Intel® UHD Graphics \n 8GB 3733MH \n 256GB M.2 PCIe ", "cijena": 2300, "popust": 30, "kolicina": 1,"img":"../../assets/images/download.jpg" , "tip": "laptop"},
    {"id": 4, "naziv": "Dell xps 15", "kratki_tekst": "10th Intel® Core™ i7-1035G1   Windows 10 Home \n Intel® UHD Graphics \n 8GB 3733MH \n 256GB M.2 PCIe ", "dugi_tekst": "10th Intel® Core™ i7-1035G1   Windows 10 Home \n Intel® UHD Graphics \n 8GB 3733MH \n 256GB M.2 PCIe ", "cijena": 2850, "popust": 30, "kolicina": 1,"img":"../../assets/images/download1.jpg" , "tip": "laptop"},
    {"id": 5, "naziv": "Dell xps 13", "kratki_tekst": "10th Intel® Core™ i5-1035G1   Windows 10 Home \n Intel® UHD Graphics \n 8GB 3733MH \n 256GB M.2 PCIe ", "dugi_tekst": "10th Intel® Core™ i5-1035G1   Windows 10 Home \n Intel® UHD Graphics \n 8GB 3733MH \n 256GB M.2 PCIe ", "cijena": 2300, "popust": 30, "kolicina": 1,"img":"../../assets/images/download.jpg" , "tip": "laptop"},
    {"id": 6, "naziv": "Iphone 11 pro", "kratki_tekst": "Apple iPhone 11 Pro MAX 512GB  \n 3 cameras 12Mp (2x zoom) \n 4K video and Face ID ", "dugi_tekst": "A transformative triple‑camera system that adds tons of capability without complexity. \n  An unprecedented leap in battery life.\n And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. \n Welcome to the first iPhone powerful enough to be called Pro. ", "cijena": 2300, "popust": 30, "kolicina": 1,"img":"../../assets/images/iphone11medium.jpg" , "tip": "mobitel"},
    {"id": 7, "naziv": "Note20", "kratki_tekst": "Samsung Galaxy Note20 Ultra 256GB (8GB RAM) \n Dynamic AMOLED  1440 x 3088", "dugi_tekst": "It's the ultimate gaming experience that goes where you go.\n   It's a director-grade 8K video camera. \n   It's a multitasking computer suite. \n   It's anything but your average smartphone ", "cijena": 2000, "popust": 15, "kolicina": 1,"img":"../../assets/images/note20.jpg" , "tip": "mobitel"},
  {"id": 8, "naziv": "Nikon Z5", "kratki_tekst": "Nikon Z 5 (Z5) Lens i Adapt Kit (w/R17560 24-50mm + FTZ mount adapter) \n 24,3 MP, 4K, WI-FI®/ BLUETOOTH®", "dugi_tekst": "Z 5 is powered by EXPEED 6 image processing system. \n NIKKOR Z lenses activate 5-axis VR image stabilization—up to five stops* of stabilization in up to five directions: yaw, pitch, roll, X and Y.  \n Freeze time with shutter speeds as fast as 1/8000 of a second ", "cijena": 3300, "popust": 5, "kolicina": 1,"img":"../../assets/images/nikon1.jpg" , "tip": "camera"},
  ]
