spring:
  application:
    name: USERS
  datasource:
    driverClassName: com.mysql.jdbc.Driver
   # url: jdbc:mysql://sql7.freemysqlhosting.net:3306/sql7282808

    #username: sql7282808
    #password: ZWzWCxQHYf
    url: jdbc:mysql://localhost:3306/users?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:

    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8081