spring:
  application:
    name: articles
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://sql7.freemysqlhosting.net:3306/sql7286303
    username: sql7286303
    password: sn67y9rl1x
  rabbitmq:
    host: localhost
    port: 5672
    username: quest
    password: quest

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sq l: true
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
